function cetak() {
  let jenisPass = document.getElementById("jenisPass").value;
  let panjangPass = document.getElementById("panjangPass").value;
  function Random(jenis, panjangPw) {
    let all = ["a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z",
      "A",
      "B",
      "C",
      "D",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "@",
      "#",
      "$",
      "_",
      "&",
      "(",
      ")",
      "/",
      "*",
      '"',
      "'",
      "~",
      "!",
      "%",
      "^",
      "-",
      "+",
      "=",
      "{",
      "[",
      "}",
      "]",
      "|",
      ",",
      ":",
      ";",
      "”",
      "‘",
      "<",
      ">",
      "?",
      "×",
      "°",
      "™"];
    let Huruf = ["a",
      "A",
      "b",
      "B",
      "c",
      "C",
      "d",
      "D",
      "e",
      "E",
      "f",
      "F",
      "g",
      "G",
      "h",
      "H",
      "i",
      "I",
      "j",
      "J",
      "k",
      "K",
      "l",
      "L",
      "m",
      "M",
      "n",
      "N",
      "o",
      "O",
      "p",
      "P",
      "q",
      "Q",
      "r",
      "R",
      "s",
      "S",
      "t",
      "T",
      "u",
      "U",
      "v",
      "V",
      "w",
      "W",
      "x",
      "X",
      "y",
      "Y",
      "z",
      "Z"];
    let Angka = ["0",
      "1",
      "3",
      "2",
      "4",
      "6",
      "5",
      "8",
      "7",
      "9"];
    let Simbol = ["@",
      "#",
      "$",
      "_",
      "&",
      "(",
      ")",
      "/",
      "*",
      '"',
      "'",
      "~",
      "!",
      "%",
      "^",
      "-",
      "+",
      "=",
      "{",
      "[",
      "}",
      "]",
      "|",
      ",",
      ":",
      ";",
      "”",
      "‘",
      "<",
      ">",
      "?",
      "×",
      "°",
      "™"];
    if (jenis == "Default") {
      for (let i = 1; i <= panjangPw; i++) {
        let RandomDefault = all[Math.floor(Math.random() *(all.length))];
        document.write(`${RandomDefault}`);
      }
    } else if (jenis == "Angka") {
      for (let i = 1; i <= panjangPw; i++) {
        let RandomAngka = Angka[Math.floor(Math.random() *(Angka.length))];
        document.write(`${RandomAngka}`);
      }
    } else if (jenis == "Simbol") {
      for (let i = 1; i <= panjangPw; i++) {
        let RandomSimbol = Simbol[Math.floor(Math.random() *(Simbol.length))];
        document.write(`${RandomSimbol}`);
      }
    } else if (jenis == "Huruf") {
      for (let i = 1; i <= panjangPw; i++) {
        let RandomHuruf = Huruf[Math.floor(Math.random() *(Huruf.length))];
        document.getElementById("Output").innerHTML = document.write(`${RandomHuruf}`);
      }
    }
  }
  panjangPass = Number(panjangPass);
  Random(jenisPass, panjangPass);
}
